import { NodeId } from '../types/simulation';

export interface NodeInfoDetail {
  id: NodeId;
  name: string;
  badge: string;
  roleSummary: string;
  description: string;
  techStack: string;
  inputs: string;
  outputs: string;
  keyResponsibilities: string[];
}

export const NODE_INFO_DATA: Record<NodeId, NodeInfoDetail> = {
  'college-db': {
    id: 'college-db',
    name: 'College Database',
    badge: 'RELATIONAL STORE',
    roleSummary: 'Central authoritative MySQL store for all structured relational data.',
    description: 'Holds quantitative facts such as tuition fee tables, lab fee breakdowns, student quotas, prerequisite GPA benchmarks, and course schedules in relational MySQL tables.',
    techStack: 'MySQL 8.0 (Offline Local Instance)',
    inputs: 'Validated SQL Query statements from SQL Query Layer.',
    outputs: 'Structured database table rows & numerical records.',
    keyResponsibilities: [
      'Executes read-only MySQL queries with low latency',
      'Provides accurate, deterministic numerical data',
      'Enforces data integrity across departments'
    ]
  },
  'sync-worker': {
    id: 'sync-worker',
    name: 'Sync Worker',
    badge: 'INGESTION WORKER',
    roleSummary: 'ETL worker that chunks, embeds, and syncs documents into the Vector Store.',
    description: 'Background daemon that parses college handbook PDFs, hostel rulebooks, and course syllabi into text chunks, generates vector embeddings, and populates the Vector DB.',
    techStack: 'Python ETL + SentenceTransformers (bge-small-en-v1.5)',
    inputs: 'Raw PDF handbooks, policy documents, and MySQL relational tables.',
    outputs: 'Vector embeddings & indexed document chunks.',
    keyResponsibilities: [
      'Automatic PDF parsing and recursive text chunking',
      'Local vector embedding generation without external APIs',
      'Periodic index synchronization with vector database'
    ]
  },
  'vector-store': {
    id: 'vector-store',
    name: 'Vector Store',
    badge: 'VECTOR DB',
    roleSummary: 'Semantic search engine storing high-dimensional vector embeddings.',
    description: 'Stores semantic representations of unstructured text documents. Allows fast similarity search to find handbook clauses matching user queries.',
    techStack: 'ChromaDB / FAISS / Qdrant (Local Persistent Index)',
    inputs: 'Query vector embedding from RAG Agent.',
    outputs: 'Top-K relevant document text chunks with similarity scores.',
    keyResponsibilities: [
      'HNSW similarity index search across thousands of chunks',
      'Returns exact page numbers and document citations',
      'Operates entirely in-memory or on local disk'
    ]
  },
  'sql-layer': {
    id: 'sql-layer',
    name: 'SQL Query Layer',
    badge: 'SECURITY & VALIDATION',
    roleSummary: 'Safety proxy that validates SQL queries against injection risks before execution.',
    description: 'Inspects generated SQL strings for safe read-only commands (SELECT only), blocks malicious SQL injection (DROP/DELETE), and checks MySQL schema compatibility.',
    techStack: 'sqlglot / AST Validator Proxy (MySQL Dialect)',
    inputs: 'Raw SQL text generated by SQL Agent.',
    outputs: 'Sanitized, validated safe MySQL query.',
    keyResponsibilities: [
      'AST validation ensuring read-only SELECT constraints',
      'MySQL schema verification preventing invalid column references',
      'Execution timeout & resource capping'
    ]
  },
  'router-agent': {
    id: 'router-agent',
    name: 'Router Agent',
    badge: 'INTENT CLASSIFIER',
    roleSummary: 'Brain of the pipeline that classifies user query intent and determines the routing strategy.',
    description: 'Analyzes user prompts to decide whether the question requires structured database facts (SQL Agent), unstructured policy search (RAG Agent), or both in parallel (Hybrid Dual-Path).',
    techStack: 'Local Zero-Shot Classifier / Small Quantized Intent Model',
    inputs: 'Raw user query text string.',
    outputs: 'Routing decision: SQL_ONLY, RAG_ONLY, or HYBRID (Parallel Dispatch).',
    keyResponsibilities: [
      'Intelligent intent detection & classification',
      'Dynamic dispatch to specialized agent workers (sequential or parallel)',
      'Minimizes unnecessary database or vector operations'
    ]
  },
  'sql-agent': {
    id: 'sql-agent',
    name: 'SQL Agent',
    badge: 'TEXT-TO-SQL AGENT',
    roleSummary: 'Specialized agent that translates natural language questions into precise MySQL queries.',
    description: 'Uses MySQL database schema metadata to convert questions about fees, grades, or intake capacity into executable SQL SELECT queries.',
    techStack: 'Local Code-Llama / Llama-3-8B Text-to-SQL Prompt Engine',
    inputs: 'User prompt + MySQL database table schemas.',
    outputs: 'Constructed MySQL SELECT statement.',
    keyResponsibilities: [
      'Translates intent into valid MySQL syntax',
      'Applies filtering, joins, and aggregations correctly',
      'Handles department code and year mappings'
    ]
  },
  'rag-agent': {
    id: 'rag-agent',
    name: 'RAG Agent',
    badge: 'SEMANTIC RETRIEVER',
    roleSummary: 'Specialized agent that retrieves relevant context from unstructured document handbooks.',
    description: 'Formulates semantic search queries, calls local embedding models, and fetches top matching PDF chunks from the Vector Store.',
    techStack: 'LangChain / LlamaIndex Retrieval Pipeline',
    inputs: 'User policy or handbook query.',
    outputs: 'Retrieved text chunks + metadata (source PDF, page numbers).',
    keyResponsibilities: [
      'Query expansion & embedding computation',
      'Vector similarity search orchestration',
      'Reranking and filtering top-K context chunks'
    ]
  },
  'local-llm': {
    id: 'local-llm',
    name: 'Local LLM Engine',
    badge: 'OFFLINE MODEL ENGINE',
    roleSummary: 'Quantized LLM running locally to generate answers without cloud dependencies.',
    description: 'Executes inference on local GPU/CPU. Combines retrieved context (MySQL facts or RAG text) to generate a coherent human response.',
    techStack: 'Ollama / llama.cpp / vLLM (Llama-3-8B-Instruct Q4_K_M)',
    inputs: 'System prompt + Retrieved facts + User query.',
    outputs: 'Raw generated text answer string.',
    keyResponsibilities: [
      '100% offline inference with zero internet connection',
      'Low latency local token generation',
      'Complete enterprise data privacy (zero cloud data egress)'
    ]
  },
  'synthesis-agent': {
    id: 'synthesis-agent',
    name: 'Synthesis Agent',
    badge: 'FUSION & GROUNDING',
    roleSummary: 'Validates response accuracy and attaches clear source provenance citations.',
    description: 'Double-checks generated numbers against MySQL database records, verifies policy statements against PDF chunks, and formats the output into clean markdown.',
    techStack: 'Fact Grounding & Citation Verifier',
    inputs: 'Generated LLM text + Raw source data.',
    outputs: 'Verified final text + Provenance tags.',
    keyResponsibilities: [
      'Hallucination prevention & factual alignment check',
      'Source provenance tagging (MySQL Table vs Vector DB PDF)',
      'Formatting bullet points and table layouts'
    ]
  },
  'chat-ui': {
    id: 'chat-ui',
    name: 'Chat UI',
    badge: 'USER INTERFACE',
    roleSummary: 'Front-facing chat interface presenting the synthesized answer to the end user.',
    description: 'Renders the final response with a smooth typing streaming effect, provenance source pills, privacy badges, and latency stats.',
    techStack: 'React + Framer Motion + Tailwind CSS',
    inputs: 'Final synthesized text + Source citations + Performance metrics.',
    outputs: 'Interactive animated answer card.',
    keyResponsibilities: [
      'Real-time response text streaming animation',
      'Displays verified sources and privacy compliance stats',
      'Provides scenario replay and prompt switching controls'
    ]
  }
};
